version: '3.8'
services:
  api:
    build:
      context: ./course-recommender-api
      dockerfile: Dockerfile.dev
    container_name: course-recommender-api
    ports:
      - '3000:3000'
    env_file:
      - course-recommender-api/.env
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/course-recommender?authSource=admin
      - AGGRIGATOR_BASE_URL=http://api2:3000
    volumes:
      - ./course-recommender-api:/app
      - ./course-recommender-api/node_modules:/app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
  api2:
    build:
      context: ./course-aggregator
      dockerfile: Dockerfile.dev
    container_name: course-course-aggregator
    ports:
      - '3000:3500'
    volumes:
      - ./course-aggregator:/app
      - ./course-aggregator/node_modules:/app/node_modules
    restart: unless-stopped
  mongo:
    image: mongo:6.0
    container_name: course-recommender-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: course-recommender
    volumes:
      - mongo_data:/data/db

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      # Uncomment and set as needed:
      # - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
    volumes:
      - chroma_data:/chroma/.chroma/index

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  chroma_data:
  mongo_data:
  # node_modules:

